services:
  - type: web
    name: talk_to_your_data
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run Chat_text_2_sql.py --server.port $PORT --server.headless true
    
